language: node_js
node_js:
  - "9"
  - "8"
script:
  - npm test
  - npm run lint
  - npm run lint:commit
cache:
  npm: true
  directories:
  - node_modules
branches:
  only:
    - master
    - "/^greenkeeper/.*$/"

